### ISSUE TITLE
I found a typo

### ISSUE THREAD

**Issue by Anonymous1157** [mdomlop/retrosmart-x11-cursors#1]
Hi! This is a nice cursor theme. Thanks for making it.

In `src/retrosmart-xcursor-white/index.theme` the English name is "Retrosmart Blanco", but all the variants are called "Retrosmart White Color/Shadow". This is inconsistent and I think it's a typo.

**Comment by mdomlop** [comment]
Already fixed in new version 2.3.1.

Thank you very much.
